name: Deploy
run-name: Deploying Pipeline!

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gather Changed Files
        id: file_changes
        uses: tj-actions/changed-files@v39
        with:
          files: "**/**"
          files_ignore: "**/README.md"
      - name: List all changed files
        run: echo '${{ steps.file_changes.outputs.all_changed_files }}'
      # - name: List files
      #   run: |
      #     echo '${{ steps.file_changes.outputs.files}}'
      #     echo '${{ steps.file_changes.outputs.files_modified}}'
      #     echo '${{ steps.file_changes.outputs.files_added}}'
      #     echo '${{ steps.file_changes.outputs.files_removed}}'
      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.2.2'
      # - name: Deploy
      #   run: ruby deploy.rb
